plugins:
  chat_enabled:
    default: false
    client: true
  chat_allowed_groups:
    client: true
    type: group_list
    list_type: compact
    default: "3" # 3 is staff group id
    allow_any: false
    refresh: true
  needs_chat_seeded:
    default: true
    hidden: true
  chat_debug_webhook_payloads:
    default: false
    hidden: true
  audio_chat_enabled:
    default: false
    client: true
